channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cpu
      - --extra-index-url https://pypi.org/simple
      - azureml-inference-server-http
      - torch
      - Pillow
      - numpy
